language: node_js
node_js:
  - "node"

  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

sudo: false

#env:
#  - LLVM_VERSION=3.4
#  - LLVM_VERSION=3.5
#  - LLVM_VERSION=3.6
#  - LLVM_VERSION=3.7

#before_install:
#  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
#  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-$LLVM_VERSION main" | sudo tee -a /etc/apt/sources.list
#  - echo "deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-$LLVM_VERSION main" | sudo tee -a /etc/apt/sources.list
#  - sudo apt-get update -qq
#  - sudo apt-get install libstdc++6-4.9
#  - sudo apt-get install llvm-$LLVM_VERSION llvm-$LLVM_VERSION-runtime libllvm$LLVM_VERSION llvm-$LLVM_VERSION-dev

# keep this infrastructure for now, look into multiple llvm versions in the future
#matrix:
#  include:
#    - os: linux
#      addons:
#        apt:
#          sources: ['llvm-toolchain-precise-3.4']
#          packages: ['libllvm3.4']
#
#    - os: linux
#      addons:
#        apt:
#          sources: ['llvm-toolchain-precise-3.5']
#          packages: ['libllvm3.5']
#
#    - os: linux
#      addons:
#        apt:
#          sources: ['llvm-toolchain-precise-3.6']
#          packages: ['libllvm3.6']
#
#    - os: linux
#      addons:
#        apt:
#          sources: ['llvm-toolchain-precise']
#          packages: ['libllvm3.7']


before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - llvm
      - gcc-4.8
      - g++-4.8

before_script:
  - llc -version || true

script:
  - npm run-script clean
  - npm run-script build
  - npm test
