language: node_js
node_js:
  - "node"
  - "iojs"

  - "0.12"
  - "0.11"
  - "0.10"

env:
  - LLVM_VERSION=3.4
  - LLVM_VERSION=3.5
  - LLVM_VERSION=3.6
  - LLVM_VERSION=3.7

before_install:
  - travis_retry sudo apt-get install llvm-$LLVM_VERSION

before_script:
  - llc -version || true

script:
  - npm run-script clean
  - npm run-script build
  - npm test
