language: node_js
node_js:
  - "node"

  - "6.1"
  - "6.0"

  - "5.11"
  - "5.10"

  - "4.4"
  - "4.3"

env:
  - CXX=g++-4.8 LLVM_CONFIG=llvm-config-3.6

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - llvm-3.6
      - llvm-3.6-dev
      - g++-4.8
      - libedit-dev

script:
  - npm run-script clean
  - npm run-script build
  - npm test
