language: node_js
node_js:
  - "node"
  - "iojs"

  - "0.12"
  - "0.11"
  - "0.10"

env:
  - LLVM_VERSION=3.4
  - LLVM_VERSION=3.5
  - LLVM_VERSION=3.6
  - LLVM_VERSION=3.7

addons:
  apt:
    sources:
      - llvm-$LLVM_VERSION

script:
  - npm run-script clean
  - npm run-script build
  - npm test
