language: node_js
node_js:
  - "node"

  - "4.2"
  - "4.1"
  - "4.0"

env:
  - CXX=g++-4.8 LLVM_CONFIG=llvm-config-3.6

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - llvm-3.6
      - llvm-3.6-dev
      - g++-4.8

before_script:
  - llc -version || true

script:
  - npm run-script clean
  - npm run-script build
  - npm test
