language: node_js
node_js:
  - "node"
  - "iojs"

  - "0.12"
  - "0.11"
  - "0.10"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install llvm

script:
  - npm run-script clean
  - npm run-script build
  - npm test
